version: "3.7"
services:

  ##############
  ## Services ##
  ##############



  links:
    image: dgoldstein1/links:2.2.0
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"
    ports:
      - 3002:3000
    environment:
      # configure reverse-proxy
      - services=biggraph,twowaykv,wikipedia,links
      ###################
      ## core services ##
      ###################
      - links_incoming_path=/
      - links_outgoing_url=file:///static-files
      - biggraph_incoming_path=/services/biggraph/
      - biggraph_outgoing_url=http://graph:5000
      - twowaykv_incoming_path=/services/twowaykv/
      - twowaykv_outgoing_url=http://kv:5001
      - wikipedia_incoming_path=/services/wiki/
      - wikipedia_outgoing_url=https://en.wikipedia.org
    volumes:
      - ./links-config.json:/static-files/config.json

  kv:
    image: dgoldstein1/twowaykv:1.0.1
    ports:
      - 5001:5001

    environment:
      - USE_S3=false
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_KV_PATH=
      - AWS_SYNC_DIRECTORY=s3://links-deployment/moby/twowaykv
      - GRAPH_DB_STORE_DIR=/db/twowaykv
      - SAVE_INTERVAL=10

  graph:
    image: dgoldstein1/biggraph:2.0.1
    ports:
      - 5000:5000
      - 8001:8001
    environment:
      - GRAPH_SAVE_INTERVAL=10
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_GRAPH_PATH=
      - AWS_SECRET_ACCESS_KEY
      - AWS_SYNC_DIRECTORY=s3://links-deployment/moby/biggraph
      - GRAPH_SAVE_PATH=/data/moby.graph
      - USE_S3=false