version: "3.7"
services:

  ##############
  ## Services ##
  ##############

  backend:
    image: dgoldstein1/links-heroku-graphapi-twowaykv:latest
    ports:
      - 8443:8443
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - READ_S3=false
      - WRITE_S3=true
      - AWS_SYNC_DIRECTORY=s3://links-deployment-dev/deployment/little-women/
      - GRAPH_SAVE_INTERVAL=30
      - PORT=8443
